apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    role-to-assume: arn:aws:iam::044135815009:role/github-ci
      username: github-ci
      groups:
        - system:masters
