apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::044135815009:user/github-ci-user
      username: github-ci
      groups:
        - system:masters
